### ISSUE TITLE
Read `kd` path from package settings

### ISSUE THREAD

**Issue by usirin** [koding/kd-atom#13]
Right now we simply assume that `kd` binary is installed somewhere included in `$PATH`. Reading it from package settings might be a good idea. We can use the current value, as default value over there.

Additionally this would make switching between `kd` and `kdx` easier as a side effect.

/cc @sinan

**Comment by sinan** [comment]
that's a good idea, even though `brew install` makes sure that it is in `$PATH`, it'd be nice that it can be overriden in the settings.

**Comment by usirin** [comment]
fixed with #21
