### ISSUE TITLE
Mount local path input is not effective

### ISSUE THREAD

**Issue by szkl** [koding/kd-atom#16]
I wanted to mount instance:/home/szkl/Projects/foo directory as /Users/sz/koding/team/foo. Local path was not respected and kd mounted remote directory to /Users/sz/koding/team/instance path which was the default.

Mount reported by `kd mount list` command is below.
/home/szkl/Projects/infra -> /Users/sz/koding/team/instance

I think this also prevents mounting multiple remote paths to local too.

**Comment by sinan** [comment]
same thing happened to me too.
